name: Text Issue
description: Report spelling, grammar, or incorrect text
title: "[TEXT] "
labels: ["text"]

body:
  - type: input
    id: location
    attributes:
      label: Location
    validations:
      required: true

  - type: textarea
    id: current_text
    attributes:
      label: Current Text
    validations:
      required: true

  - type: textarea
    id: suggested_text
    attributes:
      label: Suggested Fix
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Version at the time of discovery
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes